FROM nvcr.io/nvidia/tensorflow:19.08-py3

LABEL Author=AnhDH

WORKDIR /app
ADD . /app

RUN python3 -m pip install -r requirements.txt

RUN ["python3", "get_images.py"]

CMD ["python3", "get_embeddings.py"]